Numpy: Numerical Python : 

Written in C. So it is not slow like Python. It also allows vectorized calculations ie. [1,2,3] * 2 = [2,4,6] but in python list it returns [1,2,3,1,2,3]

Provides speed and tools to handle large scale numerical operations efficiently.

In [7]:
import numpy as np 

print(np.__version__)

my_list = [1,2,3,4]

my_multiplied_list = [1,2,3,4] * 3

print(my_list)

print(my_multiplied_list)

2.4.6
[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [8]:
import numpy as np 

array = np.array([1,2,3,5])

multiplied_array = array *2

print(array)

print(type(array))

print(multiplied_array)

[1 2 3 5]
<class 'numpy.ndarray'>
[ 2  4  6 10]


Multidimension array 

In [ ]:
import numpy as np

array = np.array([
                            [['A', 'B', 'C', 'D'], [1,2,3,4] , [3,6,7,8] , [7,8,5,3]] ,
                            [[1,2,3,8], [2,4,5,8], [3,8,8,8], [4,5,5,' ']]
    
                ])

print(array)

print(array.ndim)          # ndim stands for number of dimensions

print(type(array))

print(array.shape)    # Output Format: (Depth , Rows , Columns)

print(array[1][2][1])    # Chain indexing


# Numpy provides multidimensional indexing aswell.

print(array[1,2,1])   #Faster than chain indexing 



[[['A' 'B' 'C' 'D']
  ['1' '2' '3' '4']
  ['3' '6' '7' '8']
  ['7' '8' '5' '3']]

 [['1' '2' '3' '8']
  ['2' '4' '5' '8']
  ['3' '8' '8' '8']
  ['4' '5' '5' ' ']]]
3
<class 'numpy.ndarray'>
(2, 4, 4)
8
8


In [53]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1], [2] , [3], [4]])

print(np.shape(array1))
print(np.shape(array2))

print(array1.shape)

print(array2.shape)

print(array1.ndim)

print(array2.ndim)

np.ndim(array1)

(1, 4)
(4, 1)
(1, 4)
(4, 1)
2
2


2

In [4]:
import numpy as np

array = np.array([
                            [['A', 'E', 'C', 'V'], ['G', 'U', 'I', 'J'] , ['K', 'S', 'G', 'W'] , ['A', 'B', 'C', 'D']] ,
                            [['L', 'Y', 'B', 'M'], ['R', 'U', 'N', 'I'], ['Q', 'O', 'C', 'F'], ['X', 'A', 'F', 'J']],
                            [['T', 'W', 'S', 'D'], ['N', 'H', 'C', 'D'], ['D', 'E', 'A', 'D'], ['R', 'P', 'T', ' ']]
    
                ])

print(array.shape)

word = array[0,0,0] + array[1,1,0] + array[2,0,2] + array[2,2,1]

print(word)


(3, 4, 4)
ARSE


Slicing :   array[start:end:step]  

Here, the ending index is exclusive meaning if start is index 0 and end is 2. It returns data at index 0 and 1 not 2. 

In [16]:
import numpy as np 

array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

print(array.ndim)
print("-----------------------------------------------------------------")
print(array[0])
print("-----------------------------------------------------------------")
print(array[0:6:1])
print("-----------------------------------------------------------------")
print(array[:3])
print("-----------------------------------------------------------------")
print(array[::2])
print("-----------------------------------------------------------------")
print(array[::-1])
print("-----------------------------------------------------------------")
print(array[::-2])


2
-----------------------------------------------------------------
[1 2 3 4]
-----------------------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------------------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------------------------------------------------
[[ 1  2  3  4]
 [ 9 10 11 12]]
-----------------------------------------------------------------
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
-----------------------------------------------------------------
[[13 14 15 16]
 [ 5  6  7  8]]


In [ ]:
import numpy as np 

array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print("-----------------------------------------------------------------")
print(array)
print("-----------------------------------------------------------------")
print(array[:,1])
print("-----------------------------------------------------------------")
print(array[1:3:1, ])
print("-----------------------------------------------------------------")
print(array[1:4:2,:3])
print("-----------------------------------------------------------------")
print(array[:,:3])
print("-----------------------------------------------------------------")
print(array[:,1])
print("-----------------------------------------------------------------")
print(array[:,1:])


-----------------------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------------------------------------------------------------
[ 2  6 10 14]
-----------------------------------------------------------------
[[ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------------------------------------------------
[[ 5  6  7]
 [13 14 15]]
-----------------------------------------------------------------
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
-----------------------------------------------------------------
[ 2  6 10 14]
-----------------------------------------------------------------
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
-----------------------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [29]:
import numpy as np 

array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

print("-----------------------------------------------------------------")
print(array[:,:])
print("-----------------------------------------------------------------")
print(array[:,::2])
print("-----------------------------------------------------------------")
print(array[:,::-1])
print("-----------------------------------------------------------------")
print(array[:2,:2])


-----------------------------------------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-----------------------------------------------------------------
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
-----------------------------------------------------------------
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
-----------------------------------------------------------------
[[1 2]
 [5 6]]


4D array

In [6]:
array = np.array([   [[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],],
                     
                     [[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],],

                     [[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],],

                     [[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                     [[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],]
                     ])

print(array.shape)

print(array.ndim)

(4, 3, 5, 4)
4


Arithematics in Numpy :

1. Scalar Arthematic : Linear operations
2. vectorized Math Function : A vector is a linear algebric term and is a single dimension like a 1D array . Using Vectorized math function we can apply function across entire array without running a loop.

In [33]:
# Scalar Arithmetic

import numpy as np

array = np.array([1,2,3])

print(array +3)
print(array -2 )

print(array * 3)

print (array/4)

print(array ** 5)

[4 5 6]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [37]:
# Vectorized Math Functions

list = np.array([1.01,2.5,3.99])

print(list)

array = np.sqrt(list)

print(array)

print(np.round(array))

print(np.floor(array))       # Round Down
 
print(np.ceil(array))         # Round Up

print(np.pi)                 

[1.01 2.5  3.99]
[1.00498756 1.58113883 1.99749844]
[1. 2. 2.]
[1. 1. 1.]
[2. 2. 2.]
3.141592653589793


In [38]:
# Exercise :


import numpy as np

radii = np.array([4,5,6])

print(np.pi * radii **2)

[ 50.26548246  78.53981634 113.09733553]


In [41]:
# Element wise operation

array1 = np.array([1,2,3])

array2 = np.array([4,5,6])

print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [48]:
# Comparision Operators

test_scores = np.array([71 , 17, 32, 52 , 21, 48 ,63, 59, 80 , 27])

print(test_scores == 80)

print(test_scores > 32)

print(test_scores < 50)

test_scores[test_scores < 32] = 0

print(test_scores)

[False False False False False False False False  True False]
[ True False False  True False  True  True  True  True False]
[False  True  True False  True  True False False False  True]
[71  0 32 52  0 48 63 59 80  0]


Broadcasting : It allows Numpy to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape.

Broadcasting can be done if the dimension of arrays follow atleast one of following 2 condtions:

1. The dimension have the same size
2. One of the dimension has a size of 1

In [57]:
import numpy as np

array1 = np.array([[1,2,3,4] , [2,4,6,8], [1,3,5,7] , [3,6,9,12] ])
array2 = np.array([[1], [2] , [3], [4]])

print(array1.shape)

print(array2.shape)

print(array1 * array2)



(4, 4)
(4, 1)
[[ 1  2  3  4]
 [ 4  8 12 16]
 [ 3  9 15 21]
 [12 24 36 48]]


In [58]:
# Multiplication using Broadcasting

array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1 * array2)


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Aggregate functions : Summarize data   (Typically returns a single value)


In [69]:
import numpy as np

array = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print("----------------------------------------------")
print(np.sum(array))
print("----------------------------------------------")
print(np.mean(array))
print("----------------------------------------------")
print(np.sum(array[0]))
print("----------------------------------------------")
print(np.mean(array[1]))
print("----------------------------------------------")
print(np.std(array))                                                        # Standard Deviation
print("----------------------------------------------")
print(np.var(array))                                                        # Variance
print("----------------------------------------------")
print(np.min(array))
print("----------------------------------------------")
print(np.max(array))
print("----------------------------------------------")
print(np.argmin(array[0]))                                                     # Position of min
print("----------------------------------------------")
print(np.argmax(array))                                                  # Position of max

----------------------------------------------
55
----------------------------------------------
5.5
----------------------------------------------
15
----------------------------------------------
8.0
----------------------------------------------
2.8722813232690143
----------------------------------------------
8.25
----------------------------------------------
1
----------------------------------------------
10
----------------------------------------------
0
----------------------------------------------
9


In [ ]:
print(np.sum(array, axis = 0))     # If axis is 0 , we are applying this function to all columns

print(np.sum(array, axis =1))        # If axis is 1 , we are applying this function to all rows

[ 7  9 11 13 15]
[15 40]


Filtering : The process of selecting elements from an array that match the given condition

In [86]:
import numpy as np

ages = np.array([[21,17,19,18,24,27,35,72,14],
                 [12,56,43,60,51,32,44,84,19]])

children = ages[ages < 18]

adults = ages[(ages >= 18)& (ages <= 60)]

seniors = ages[ages >=65]

teenagers = ages[(ages<20)&(ages>12)]

print(f"Even ages are: {ages[ages%2 == 0]}")
print(f"Odd ages are: {ages[ages%2 !=0]}")

print(adults)
print(children)
print(seniors)
print(teenagers)

Even ages are: [18 24 72 14 12 56 60 32 44 84]
Odd ages are: [21 17 19 27 35 43 51 19]
[21 19 18 24 27 35 56 43 60 51 32 44 19]
[17 14 12]
[72 84]
[17 19 18 14 19]


In [ ]:
# Syntax of where filtering.   np.where(condition, array , fill_value).   # Fill_value is used to preserve original shape.
# where clause is generally slower than boolean indexing/filteriing. So used only when shape preservation is required.

import numpy as np

ages = np.array([[21,17,19,18,24,27,35,72,14],
                 [12,56,43,60,51,32,44,84,19]])


adults = np.where(ages >=18, ages, 0)   # Other commonly used fill values are : -1 or np.nan       (not a number)
print(adults)

[[21  0 19 18 24 27 35 72  0]
 [ 0 56 43 60 51 32 44 84 19]]


Random Numbers

In [ ]:
import numpy as np

dice = np.random.default_rng()

print(dice.integers(1,7))              # Second number is exclusive . So it will give a random number from 1 to 6

print(dice.integers(low=1 , high = 51 , size = 3))     # Same thing just more readable . Size gives how many numbers to generate.

rng = np.random.default_rng()

print(rng.integers(1,51,(3,2)))


rng2 = np.random.default_rng(seed = 1)

print(rng2.integers(1,41))   # Seed helps to generate same random number. Useful when we want to reproduce the same result.


4
[46  7 32]
[[ 4 45]
 [43 10]
 [34 24]]
19


In [141]:
print(np.random.uniform())        # prints a random floating point number between 0 and 1

print("-------------------------------------------------------------")

np.random.seed(1)  # or np.random.seed(seed = 1)
print(np.random.uniform(1,-1, size = (2,3)))


0.1862602113776709
-------------------------------------------------------------
[[ 0.16595599 -0.44064899  0.99977125]
 [ 0.39533485  0.70648822  0.81532281]]


In [145]:
array = np.array([1,2,3,4,5])

print(array)
print("---------------------------------------------------------")
rng = np.random.default_rng()

rng.shuffle(array)

print (array)

print("---------------------------------------------------------")

fruits = np.array(['Apple', 'Banana' , 'Coconut', 'Strawberry' , 'Litchi', 'Pineapple', 'Watermelon' , 'Mango'])

print(fruits)
print("---------------------------------------------------------")

fruit = rng.choice(fruits,size = 3)

print(fruit)





[1 2 3 4 5]
---------------------------------------------------------
[2 4 3 5 1]
---------------------------------------------------------
['Apple' 'Banana' 'Coconut' 'Strawberry' 'Litchi' 'Pineapple' 'Watermelon'
 'Mango']
---------------------------------------------------------
['Litchi' 'Mango' 'Litchi']
